vpn_mgmt_v8/app/mgmt/forms.py
#!/usr/bin/env python
# coding: utf-8
# author: songjianhao
# e-mail: fredmail03@126.com
# Pw @ 2016-04-26 15:50

import sys
reload(sys)
sys.setdefaultencoding('utf8')
from flask.ext.wtf import Form
from wtforms import StringField,PasswordField,SelectField,SubmitField
from wtforms.validators import Required,Regexp,Length,Email,EqualTo
from wtforms import ValidationError
from ..models import User

class RegisterForm(Form):
    username = StringField('用户名:',validators=[Required(),Length(1-64),
                                                   Regexp('^[A-Za-z][A-Za-z0-9._]*$',0,
                                                          'Usernames must have only letters,'
                                                          'numbers, dot or underscores')])
    password_login = PasswordField('密码:',validators=[Required(),
                                                           EqualTo('password_vpn',
                                                                   message='密码必须匹配.')])
    password_vpn = PasswordField('确认密码:',validators=[Required()])
    name = StringField('姓名:',validators=[Required(),Length(1,60)])
    role = SelectField('角色:',choices =[('vpn','vpn'),('admin','admin')])
    email = StringField('邮箱',validators=[Required(),Length(1,60),Email()])
    submit = SubmitField('添加')

    def validate_username(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('该用户名已经存在.')

    def validate_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('该邮箱已经存在.')

class MgmtChpasswdForm(Form):
    username = StringField('用户名:',validators=[Required(),
                                                   Length(1,64),
                                                   Regexp('^[A-Za-z][A-Za-z0-9._]*$',0,
                                                          'Username must have only letter,'
                                                          'numbers,dot,understanders')])
    password_login = PasswordField('密码:',validators=[Required(),
                                                           EqualTo('password_vpn',
                                                                   message='密码不匹配')])
    password_vpn = PasswordField('确认密码：',validators=[Required()])
    submit = SubmitField('修改')

class FindUserForm(Form):
    username = StringField('用户名：',validators=[Required(),
                                              Length(1,64),Regexp('[A-Za-z][A-Za-z0-9._]*$',0,
                                                                  'Username must have only letter,'
                                                                  'numbers dot,nuderstanders')])
    submit = SubmitField('查询')

vpn_mgmt_v8/app/mgmt/__init__.py
#!/usr/bin/env python
# coding: utf-8
# author: songjianhao
# e-mail: fredmail03@126.com
# Pw @ 2016-04-26 15:50

import sys
reload(sys)
sys.setdefaultencoding('utf8')
from flask import Blueprint

mgmt = Blueprint('mgmt',__name__)

from . import views

vpn_mgmt_v8/app/mgmt/views.py
#!/usr/bin/env python
# coding: utf-8
# author: songjianhao
# e-mail: fredmail03@126.com
# Pw @ 2016-04-26 15:50

import sys
reload(sys)
sys.setdefaultencoding('utf8')
from flask import flash,render_template,url_for,redirect
from . import mgmt
from .forms import RegisterForm,MgmtChpasswdForm,FindUserForm
from flask.ext.login import login_required
from ..models import User,db
from .. import mysql

@mgmt.route('/register',methods=['GET','POST'])
@login_required
def register():
    form = RegisterForm()
    cur = mysql.connect.cursor()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    password=form.password_login.data,
                    email=form.email.data,
                    name=form.name.data,
                   role=form.role.data)
        db.session.add(user)
        db.session.commit()
        #print "passwod_vpn=%s" % form.password_vpn.data
        sql = "insert into user(username,password,name,email) VALUES ('%s',encrypt('%s'),'%s','%s')" % (form.username.data,form.password_login.data,form.name.data,form.email.data)
#        print "sql=%s" % sql
        cur.execute(sql)
        mysql.connect.commit()
        flash('您添加用户成功')
    return render_template('mgmt/register.html',form=form)

@mgmt.route('/adminHome')
@login_required
def adminHome():
    return render_template('mgmt/adminHome.html')

@mgmt.route('/mgmtchpasswd',methods=['GET','POST'])
@login_required
def mgmtChpasswd():
    form = MgmtChpasswdForm()
    cur = mysql.connect.cursor()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None:
            flash("您输入的用户不存在")
            return redirect(url_for('.mgmtChpasswd'))
        user.password = form.password_login.data
        db.session.add(user)
        db.session.commit()
        sql = "update user set password = encrypt('%s') where username='%s'" % (form.password_login.data,form.username.data)
        #print "update sql = '%s'" % sql
        cur.execute(sql)
        flash("密码修改成功")
    return render_template('mgmt/mgmtChpasswd.html',form=form)

@mgmt.route('/FindUser',methods=['GET','POST'])
@login_required
def FindUser():
    form = FindUserForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None:
            flash("您输入的用户名不存在")
        else:
            userinfo = User.query.filter_by(username=form.username.data).all()
            return render_template('mgmt/FindUser.html',form=form,userinfo=userinfo)
    return render_template('mgmt/FindUser.html',form=form)

@mgmt.route('/select')
@login_required
def select():
    return render_template('mgmt/test.html')

vpn_mgmt_v8/app/templates/mgmt/FindUser.html
{% extends "mgmt/adminbase.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}FindUser{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>用户查询</h1>
</div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}

    </br>
        <table class="table table-bordered table-hover">
        <tr>
            <th>用户名</th>
            <th>姓名</th>
            <th>邮箱</th>
        </tr>
        {% for usero in userinfo %}
        <tr>
            <td>{{ usero.username }}</td>
            <td>{{ usero.name }}</td>
            <td>{{ usero.email }}</td>
        </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}

vpn_mgmt_v8/app/templates/mgmt/adminbase.html
{% extends "base.html" %}
 {% block item %}
     <li><a href="{{ url_for('mgmt.register') }}">添加账号</a></li>
     <li><a href="{{ url_for('mgmt.mgmtChpasswd')}}">修改用户密码</a></li>
     <li><a href="{{ url_for('mgmt.FindUser')}}">用户查询</a></li>
 {% endblock %}

vpn_mgmt_v8/app/templates/mgmt/mgmtChpasswd.html
{% extends "mgmt/adminbase.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}change_passwd{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1>修改VPN用户密码</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

vpn_mgmt_v8/app/templates/mgmt/register.html
{% extends "mgmt/adminbase.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}register{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1>添加VPN用户</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

vpn_mgmt_v8/app/templates/mgmt/test.html
{% extends "mgmt/adminbase.html"  %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}test{% endblock %}
{% block page_content %}
    <div class="panel">
      this is test page
    </div>
{% endblock %}